package src.view;

import java.awt.event.KeyEvent;
import javax.swing.JDialog;

/**
 * This class will display a JDialog that provides a GUI to allow the user to
 * create an AdvancedFilter of up to 5 terms.  
 * 
 * @author Robert Kanter
 * @author Brenda Medina
 */
public class AdvancedFilterCreatorDialog extends javax.swing.JPanel {
    
    /**
     * The JLogger
     */
    private JLogger logger;
    /**
     * The dialog that we're displaying
     */
    private JDialog myDialog;

    /**
     * The constructor sets logger to the passed in argument.  It then calls
     * initComponents() to setup the GUI.  Lastly, it does what is necessary to
     * create and display the JDialog.  
     * 
     * @param log
     */
    public AdvancedFilterCreatorDialog(JLogger log) {
        logger = log;
        initComponents();

        //Display the JDialog
        myDialog = new JDialog(logger, "Create Advanced Filter", true);
        myDialog.setContentPane(this);
        myDialog.pack();
        //myDialog.setResizable(false);
        myDialog.setLocationRelativeTo(logger);
        myDialog.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup1 = new javax.swing.ButtonGroup();
        typeGroup2 = new javax.swing.ButtonGroup();
        typeGroup3 = new javax.swing.ButtonGroup();
        typeGroup4 = new javax.swing.ButtonGroup();
        typeGroup5 = new javax.swing.ButtonGroup();
        LogicalOperatorGroup = new javax.swing.ButtonGroup();
        filterField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        positiveRadioButton1 = new javax.swing.JRadioButton();
        negativeRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        positiveRadioButton2 = new javax.swing.JRadioButton();
        negativeRadioButton2 = new javax.swing.JRadioButton();
        filterField2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        positiveRadioButton3 = new javax.swing.JRadioButton();
        negativeRadioButton3 = new javax.swing.JRadioButton();
        filterField3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        positiveRadioButton4 = new javax.swing.JRadioButton();
        negativeRadioButton4 = new javax.swing.JRadioButton();
        filterField4 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        positiveRadioButton5 = new javax.swing.JRadioButton();
        negativeRadioButton5 = new javax.swing.JRadioButton();
        filterField5 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        AndjRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        OrjRadioButton = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();

        filterField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Filter 1:");

        jLabel2.setText("Type:");

        typeGroup1.add(positiveRadioButton1);
        positiveRadioButton1.setSelected(true);
        positiveRadioButton1.setText("Positive");

        typeGroup1.add(negativeRadioButton1);
        negativeRadioButton1.setText("Negative");

        jLabel3.setText("Enter up to 5 filters:");

        jLabel4.setText("Filter 2:");

        jLabel5.setText("Type:");

        typeGroup2.add(positiveRadioButton2);
        positiveRadioButton2.setSelected(true);
        positiveRadioButton2.setText("Positive");

        typeGroup2.add(negativeRadioButton2);
        negativeRadioButton2.setText("Negative");

        filterField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterField2KeyReleased(evt);
            }
        });

        jLabel6.setText("Filter 3:");

        jLabel7.setText("Type:");

        typeGroup3.add(positiveRadioButton3);
        positiveRadioButton3.setSelected(true);
        positiveRadioButton3.setText("Positive");

        typeGroup3.add(negativeRadioButton3);
        negativeRadioButton3.setText("Negative");

        filterField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterField3KeyReleased(evt);
            }
        });

        jLabel8.setText("Filter 4:");

        jLabel9.setText("Type:");

        typeGroup4.add(positiveRadioButton4);
        positiveRadioButton4.setSelected(true);
        positiveRadioButton4.setText("Positive");

        typeGroup4.add(negativeRadioButton4);
        negativeRadioButton4.setText("Negative");

        filterField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterField4KeyReleased(evt);
            }
        });

        jLabel10.setText("Filter 5:");

        jLabel11.setText("Type:");

        typeGroup5.add(positiveRadioButton5);
        positiveRadioButton5.setSelected(true);
        positiveRadioButton5.setText("Positive");

        typeGroup5.add(negativeRadioButton5);
        negativeRadioButton5.setText("Negative");

        filterField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterField5KeyReleased(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        LogicalOperatorGroup.add(AndjRadioButton);
        AndjRadioButton.setSelected(true);
        AndjRadioButton.setText("And");

        jLabel12.setText("Logical Operator:");

        LogicalOperatorGroup.add(OrjRadioButton);
        OrjRadioButton.setText("Or");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(260, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(positiveRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(negativeRadioButton1))
                    .addComponent(filterField1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(positiveRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(negativeRadioButton2))
                    .addComponent(filterField2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(positiveRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(negativeRadioButton4))
                    .addComponent(filterField4, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(createButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterField5, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(positiveRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(negativeRadioButton5)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(AndjRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrjRadioButton)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(positiveRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(negativeRadioButton3))
                            .addComponent(filterField3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filterField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(negativeRadioButton1)
                    .addComponent(positiveRadioButton1))
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(filterField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(negativeRadioButton2)
                    .addComponent(positiveRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(filterField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(negativeRadioButton3)
                    .addComponent(positiveRadioButton3))
                .addGap(9, 9, 9)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(filterField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(negativeRadioButton4)
                    .addComponent(positiveRadioButton4))
                .addGap(9, 9, 9)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(filterField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(negativeRadioButton5)
                    .addComponent(positiveRadioButton5))
                .addGap(20, 20, 20)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AndjRadioButton)
                    .addComponent(OrjRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

     /**
     * ActionListener for the "Cancel" button.  It simply closes myDialog.
     *
     * @param evt The ActionEvent
     */    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        myDialog.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * ActionListener for the "Create" button.  For each filterField that is not empty,
     * it will create an AdvancedFilterObject (contains a String and a boolean).  It
     * will then close the dialog.  Then it passes an array of the AdvancedFilterObjects
     * and whether the user selected the logical operator 'and' or not
     * to JLogger's createAdvancedFilter() method.  If there were no
     * AdvancedFilterObjects created (i.e. all of the filterFields were empty), it
     * will just return.
     *
     * @param evt The ActionEvent
     */
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
       String f1 = filterField1.getText();
        boolean b1 = positiveRadioButton1.isSelected();
        //Get the second filter
        String f2 = filterField2.getText();
        boolean b2 = positiveRadioButton2.isSelected();
        //Get the third filter
        String f3 = filterField3.getText();
        boolean b3 = positiveRadioButton3.isSelected();
        //Get the fourth filter
        String f4 = filterField4.getText();
        boolean b4 = positiveRadioButton4.isSelected();
        //Get the fifth filter
        String f5 = filterField5.getText();
        boolean b5 = positiveRadioButton5.isSelected();
        //Figure out how many filters are actually being used
        int numFilters = 0;
        if(f1.length() != 0) numFilters++;
        if(f2.length() != 0) numFilters++;
        if(f3.length() != 0) numFilters++;
        if(f4.length() != 0) numFilters++;
        if(f5.length() != 0) numFilters++;
        //Create an array of AdvancedFilterObjects
        AdvancedFilterObject[] filts = new AdvancedFilterObject[numFilters];

        //For each filter that is not empty, create an AdvancedFilterObject and add
        //it to the array
        int i=0;
        if(f1.length() != 0)
        {
            filts[i] = new AdvancedFilterObject(f1, b1);
            i++;
        }
        if(f2.length() != 0)
        {
            filts[i] = new AdvancedFilterObject(f2, b2);
            i++;
        }
       if(f3.length() != 0)
        {
            filts[i] = new AdvancedFilterObject(f3, b3);
            i++;
        }
       if(f4.length() != 0)
        {
            filts[i] = new AdvancedFilterObject(f4, b4);
            i++;
        }
       if(f5.length() != 0)
        {
            filts[i] = new AdvancedFilterObject(f5, b5);
            i++;
        }

        //Close the dialog
        myDialog.setVisible(
        false);

        //If no AdvancedFilterObjects were created, return
        if(filts.length == 0) return;

        //Call createAdvancedFilter() and give it the array
        logger.createAdvancedFilter(filts, AndjRadioButton.isSelected());
    }//GEN-LAST:event_createButtonActionPerformed

    /**
     * Action Listener that allows the user to press enter after typing in the first text field to create an advanced filter
     * @param evt
     */
    private void filterField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterField1KeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            createButton.doClick();
        }
    }//GEN-LAST:event_filterField1KeyReleased

    /**
     * Action Listener that allows the user to press enter after typing in the second text field to create an advanced filter
     * @param evt
     */
    private void filterField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterField2KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                createButton.doClick();
            }
    }//GEN-LAST:event_filterField2KeyReleased

    /**
     * Action Listener that allows the user to press enter after typing in the third text field to create an advanced filter
     * @param evt
     */
    private void filterField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterField3KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                createButton.doClick();
            }
    }//GEN-LAST:event_filterField3KeyReleased

    /**
     * Action Listener that allows the user to press enter after typing in the fourth text field to create an advanced filter
     * @param evt
     */
    private void filterField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterField4KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                createButton.doClick();
            }
    }//GEN-LAST:event_filterField4KeyReleased

    /**
     * Action Listener that allows the user to press enter after typing in the 5th text field to create an advanced filter
     * @param evt
     */
    private void filterField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterField5KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                createButton.doClick();
            }
    }//GEN-LAST:event_filterField5KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AndjRadioButton;
    private javax.swing.ButtonGroup LogicalOperatorGroup;
    private javax.swing.JRadioButton OrjRadioButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField filterField1;
    private javax.swing.JTextField filterField2;
    private javax.swing.JTextField filterField3;
    private javax.swing.JTextField filterField4;
    private javax.swing.JTextField filterField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JRadioButton negativeRadioButton1;
    private javax.swing.JRadioButton negativeRadioButton2;
    private javax.swing.JRadioButton negativeRadioButton3;
    private javax.swing.JRadioButton negativeRadioButton4;
    private javax.swing.JRadioButton negativeRadioButton5;
    private javax.swing.JRadioButton positiveRadioButton1;
    private javax.swing.JRadioButton positiveRadioButton2;
    private javax.swing.JRadioButton positiveRadioButton3;
    private javax.swing.JRadioButton positiveRadioButton4;
    private javax.swing.JRadioButton positiveRadioButton5;
    private javax.swing.ButtonGroup typeGroup1;
    private javax.swing.ButtonGroup typeGroup2;
    private javax.swing.ButtonGroup typeGroup3;
    private javax.swing.ButtonGroup typeGroup4;
    private javax.swing.ButtonGroup typeGroup5;
    // End of variables declaration//GEN-END:variables

}