package src.view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;

/**
 * This class will display a JDialog that provides a GUI to allow the user to
 * Search the messages
 * 
 * @author Brenda Medina
 */
public class SearchDialog extends javax.swing.JPanel {
    
    /**
     * The JLogger
     */
    private JLogger logger;
    /**
     * The dialog that we're displaying
     */
    private JDialog myDialog;

    /**
     * The constructor sets logger to the passed in argument.  It then calls
     * initComponents() to setup the GUI.  Lastly, it does what is necessary to
     * create and display the JDialog.  
     * 
     * @param log
     */
    public SearchDialog(JLogger log) {
        logger = log;
        initComponents();

        //Display the JDialog
        myDialog = new JDialog(logger, "Search", true);
        myDialog.setContentPane(this);
        myDialog.pack();
        //myDialog.setResizable(false);
        myDialog.setLocationRelativeTo(logger);
        myDialog.setVisible(true);
        searchField.setText(logger.getSearchText());
    }
    /*
     * Added by Apar Suri
     * This method is to send the text of the searchtextbox to the logger
     */
     public String getSearchText() {
         return this.searchField.getText();
     }

      /*
     * Added by Apar Suri
     * This method is to set the text of the searchtextbox
     */
     public void setSearchText(String value, Color c) {
         this.searchField.setForeground(c);
         this.searchField.setText(value);
     }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup1 = new javax.swing.ButtonGroup();
        typeGroup2 = new javax.swing.ButtonGroup();
        typeGroup3 = new javax.swing.ButtonGroup();
        typeGroup4 = new javax.swing.ButtonGroup();
        typeGroup5 = new javax.swing.ButtonGroup();
        LogicalOperatorGroup = new javax.swing.ButtonGroup();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        previousjButton = new javax.swing.JButton();
        jLabelSearchStatus = new javax.swing.JLabel();

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("Find What:");

        NextButton.setText("Find Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        previousjButton.setText("Find Previous");
        previousjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousjButtonActionPerformed(evt);
            }
        });

        jLabelSearchStatus.setName("searchStatus"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSearchStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousjButton)
                            .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSearchStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

     /**
     * ActionListener for the "Cancel" button.  It simply closes myDialog.
     *
     * @param evt The ActionEvent
     */    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        myDialog.setVisible(false);
        logger.setSearchText( this.searchField.getText());
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Ation LIstener for the FInd next button: searches and highlights the next instance
     *
     * @param evt The ActionEvent
     */
    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
      String text = searchField.getText();
        if(text.trim().compareTo("") == 0){
            return;
        }
        logger.searchForwarFor(text);
}//GEN-LAST:event_NextButtonActionPerformed

    /**
     * Action Listener that allows the user to press F3 or enter for the next instance or shift+F3 for the previous one
     * @param evt
     */
    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           logger.resetSearchSetting();
           NextButton.doClick();
       }else if(evt.isShiftDown() && evt.getKeyCode() == KeyEvent.VK_F3){
        previousjButton.doClick();
      }else if (evt.getKeyCode() == KeyEvent.VK_F3) {
        NextButton.doClick();
      }
}//GEN-LAST:event_searchFieldKeyReleased

     /**
     * Ation Listener for the FInd next button: searches and highlights the prevgious instance
     *
     * @param evt The ActionEvent
     */
    private void previousjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousjButtonActionPerformed
        String text = searchField.getText();
        if(text.trim().compareTo("") == 0){
            return;
        }
        logger.searchBackwardFor(text);
    }//GEN-LAST:event_previousjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup LogicalOperatorGroup;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSearchStatus;
    private javax.swing.JButton previousjButton;
    private javax.swing.JTextField searchField;
    private javax.swing.ButtonGroup typeGroup1;
    private javax.swing.ButtonGroup typeGroup2;
    private javax.swing.ButtonGroup typeGroup3;
    private javax.swing.ButtonGroup typeGroup4;
    private javax.swing.ButtonGroup typeGroup5;
    // End of variables declaration//GEN-END:variables

}